###
GET {{baseUrl}}/internal/isAlive
Accept: */*

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET {{baseUrl}}/internal/isReady
Accept: */*

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET {{baseUrl}}/internal/metrics
Accept: */*

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
# @no-redirect
GET {{baseUrl}}/login
Accept: */*

###
GET {{baseUrl}}/logout
Accept: */*

###
# @no-redirect
GET {{baseUrl}}/oauth2/callback
Accept: */*

###
GET {{baseUrl}}/api/does-not-exist
Accept: */*

###
# @no-redirect
GET {{baseUrl}}/
Accept: */*

###
GET {{baseUrl}}/asset-manifest.json
Accept: */*

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET {{baseUrl}}/settings.js
Accept: */*

###
# @no-redirect
GET {{baseUrl}}/does-not-exist
Accept: */*

###
GET {{baseUrl}}/mockServiceWorker.js
Accept: */*

###
GET http://localhost:5000/mockServiceWorker.js
Accept: */*

###
GET {{baseUrl}}/api/altinn/api/serviceowner/delegationRequests
Accept: */*
