apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: hm-delbestilling
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{image}}
  port: 5000
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  liveness:
    path: /hjelpemidler/delbestilling/internal/isAlive
    initialDelay: 5
  readiness:
    path: /hjelpemidler/delbestilling/internal/isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /hjelpemidler/delbestilling/internal/metrics
  ingresses:
    - https://www.nav.no/hjelpemidler/delbestilling
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
  env:
    - name: API_URL
      value: http://hm-delbestilling-api.teamdigihot.svc.cluster.local
    - name: DELBESTILLING_API_AUDIENCE
      value: prod-gcp:teamdigihot:hm-delbestilling-api
    - name: ROLLER_URL
      value: http://hm-roller.teamdigihot.svc.cluster.local
    - name: ROLLER_AUDIENCE
      value: prod-gcp:teamdigihot:hm-roller
    - name: REDIRECT_URL
      value: https://www.nav.no/hjelpemidler/delbestilling
    - name: USE_MSW
      value: 'false'
    - name: GIT_COMMIT
      value: {{commit}}
  accessPolicy:
    outbound:
      external:
        - host: www.nav.no
        - host: loginservice.nav.no
      rules:
        - application: hm-delbestilling-api
        - application: hm-roller
        - application: nav-dekoratoren
          namespace: personbruker
